-- create.sql

-- Criação da sequence
CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Criação da tabela TB_CLIENTE
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE,
    CEP VARCHAR2(8),
    LOGRADOURO VARCHAR2(255),
    BAIRRO VARCHAR2(255),
    CIDADE VARCHAR2(255),
    UF CHAR(2),
    ATIVO NUMBER(1) DEFAULT 1,
    DT_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP,
    DT_ATUALIZACAO TIMESTAMP
);

-- Constraints adicionais
ALTER TABLE TB_CLIENTE ADD CONSTRAINT CHK_UF CHECK (
    UF IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')
);

-- Trigger BEFORE INSERT para popular ID_CLIENTE e DT_CRIACAO
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BI
BEFORE INSERT ON TB_CLIENTE
FOR EACH ROW
BEGIN
    :NEW.ID_CLIENTE := SEQ_CLIENTE.NEXTVAL;
    :NEW.DT_CRIACAO := SYSTIMESTAMP;
END;
/

-- Trigger BEFORE UPDATE para atualizar DT_ATUALIZACAO
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BU
BEFORE UPDATE ON TB_CLIENTE
FOR EACH ROW
BEGIN
    :NEW.DT_ATUALIZACAO := SYSTIMESTAMP;
END;
/